version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: [ "python", "main.py" ]

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    deploy:
      replicas: 3
    command: [ "python", "main.py" ]
